name: cargo

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        apt-get update -y
        apt-get install -y clang \
          libclang1 \
          libeccodes-dev
        rustup update stable
        cargo install cargo-criterion
        cargo clean
    - name: Build with cargo
      run: |
        cargo build --release
        cargo clean
    - name: Test with cargo
      run: |
        cargo test
        cargo clean
    - name: Benchmark with criterion
      run: |
        cargo criterion
        cargo clean
